### ISSUE TITLE
TFRs were mentioned in a presentation of this--what are they?

### ISSUE THREAD

**Issue by douglasnaphas** [iloveicedgreentea/DevOops#1]
In a [HashiCorp User Group meeting](https://www.youtube.com/watch?v=r--A1iaulu0&t=940s) where this was presented, *TFRs* were mentioned. I couldn't find anything online about this concept (searching for acronyms is hard).

What are TFRs?

If anyone can provide a reference, I can do a PR adding a link to [this line](https://github.com/iloveicedgreentea/DevOops/blame/915d75447ba56ba8798dbd92a38ffe6f578894b4/readme.md#L16).

**Comment by iloveicedgreentea** [comment]
TFRs sounds a lot like "tf vars" out loud. Is that what you are referring to? That would be part of `*.tfvars` and using `var.xyz`

**Comment by douglasnaphas** [comment]
Thanks! I did indeed hear `.tfvars` as "TFRs." Closing this issue.
